# Generated by Django 4.2.10 on 2024-03-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_accountid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
