# Generated by Django 4.2.10 on 2024-02-29 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('TeamID', models.AutoField(primary_key=True, serialize=False)),
                ('TeamName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Spreads',
            fields=[
                ('SpreadID', models.AutoField(primary_key=True, serialize=False)),
                ('PointDiff', models.DecimalField(decimal_places=1, max_digits=3)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('Year', models.IntegerField()),
                ('Week', models.IntegerField()),
                ('DogID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='DogID', to='picks.teams')),
                ('FavID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='FavID', to='picks.teams')),
            ],
        ),
        migrations.CreateModel(
            name='Picks',
            fields=[
                ('PickID', models.AutoField(primary_key=True, serialize=False)),
                ('PickName', models.CharField(max_length=30)),
                ('PickText', models.TextField()),
                ('GroupXAccountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groupxaccount')),
                ('SpreadID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='picks.spreads')),
            ],
        ),
        migrations.CreateModel(
            name='Outcomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PointDiff', models.DecimalField(decimal_places=1, max_digits=3)),
                ('SpreadID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='picks.spreads')),
                ('WinTeamID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='picks.teams')),
            ],
        ),
    ]
