# Generated by Django 4.2.10 on 2024-03-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_adminid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupxaccount',
            name='AccountID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='groupxaccount',
            name='GroupID',
            field=models.IntegerField(),
        ),
    ]
