# Generated by Django 4.2.10 on 2024-03-17 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_adminid_alter_groupxaccount_accountid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='AdminID',
            new_name='Admin',
        ),
        migrations.RenameField(
            model_name='groupxaccount',
            old_name='AccountID',
            new_name='Account',
        ),
        migrations.RenameField(
            model_name='groupxaccount',
            old_name='GroupID',
            new_name='Group',
        ),
    ]
